hmrc/agent-invitations-frontend

- app/ErrorHandler.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentConfirmationLinkFlagTrueISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/support/BaseISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/support/WireMockSupport.scala
and port other fixes from agents-frontend template
> [AO] add missing error auditing

- app/ErrorHandler.scala
- app/FrontendModule.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/Services.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/personalincomerecord/PirClientRelationshipController.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/PirClientRelationshipControllerISpec.scala
> [APB-1917][PT]: Refactor controllers, added constance and update tests

- app/uk/gov/hmrc/agentinvitationsfrontend/binders/UrlBinders.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/connectors/InvitationsConnector.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/services/InvitationsService.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/complete.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/confirm_terms.scala.html
- conf/application.conf
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/connectors/InvitationsConnectorISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/stubs/AuthStubs.scala
Add VAT support for Client Journey
> [APB-1884]: Client responds to invite for MTD-VAT

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AuthActions.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/not_authorised.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/connectors/AuthActionsISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/PirClientRelationshipControllerISpec.scala
squash commits, remove the fixed appropriate tests
> Apb 1946 provide an unauthorised page for PIR when no HMRC-NI enrolment

- build.sbt
This change has been forced by bobby:
```
[info] +-------+-------------------------------------------+--------------+---------------+----------------+------------+
[info] | Level | Dependency                                | Your Version | Invalid Range | Latest Version | Deadline   |
[info] +-------+-------------------------------------------+--------------+---------------+----------------+------------+
[info] | ERROR | uk.gov.hmrc.bootstrap-play-25             | 1.2.0        | (,1.4.0)      | 1.5.0          | 2018-03-16 |
[info] | INFO  | com.github.tomakehurst.wiremock           | 2.12.0       | -             | (Not found)    | -          |
[info] | INFO  | de.threedimensions.metrics-play           | 2.5.13       | -             | (Not found)    | -          |
[info] | INFO  | …
```
> [APB-2194][AO] upgrade libraries

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsInvitationController.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsControllerShowFlagsOffISpec.scala
- test/extractors/AgentInvitationsFastTrackExtractorsSpec.scala
Also cleared out cache at the end of journey to allow user to create another invitation that may use a similar client identifier.
> [APB-2332]: Refined integration with FeatureFlags and updated tests

- app/uk/gov/hmrc/agentinvitationsfrontend/connectors/InvitationsConnector.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsRequestTrackingController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/testing/TestEndpointsController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/confirm_cancel.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/pending_form.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/recent_invitations.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/request_cancelled.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/connectors/InvitationsConnectorISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsRequestTrackingControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/stubs/ACAStubs.scala
- test/forms/CancelRequestFormSpec.scala
I made up some of the URLs and error messages in this PR, should be checked by Ian Cuddy when he returns.
> [APB-2863][MP] Adding action to cancel an invitation, 2 new pages for micro-journey, with tests

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/testing/TestEndpointsController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/AgentInvitationForm.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/FastTrackInvitation.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/Services.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/business_select_service.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/personal_select_service.scala.html
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerFastTrackISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerWithPasscodeISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsControllerShowFlagsOffISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsIRVControllerJourneyISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsVATControllerJourneyISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/FastTrackIRVISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/FastTrackITSAISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/FastTrackVatISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/services/FastTrackKeyStoreCacheSpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/support/TestDataCommonSupport.scala
- test/audit/AuditSpec.scala
- test/extractors/AgentInvitationKfcExtractorSpec.scala
- test/extractors/CurrentInvitationInputExtractorsSpec.scala
- test/forms/AgentClientTypeFormSpec.scala
- test/forms/AgentInvitationIdentifyClientFormIrvSpec.scala
- test/forms/AgentInvitationIdentifyClientFormItsaSpec.scala
- test/forms/AgentInvitationIdentifyClientFormVatSpec.scala
- test/forms/AgentInvitationPostcodeFormSpec.scala
- test/forms/AgentInvitationServiceFormSpec.scala
> [APB-3093][APB-3098][PT]: Change to Personal and Business Service Pages plus Update tests

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerSupport.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/DateFieldHelper.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/forms/IrvClientForm.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/forms/ItsaClientForm.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/forms/VatClientForm.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/IrvClient.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/ItsaClient.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/VatClient.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/validators/Validators.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/identify_client_irv.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/identify_client_itsa.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/identify_client_vat.scala.html
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationControllerKFCFlagsOppositeISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsIRVControllerJourneyISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsITSAControllerJourneyISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsVATControllerJourneyISpec.scala
- test/forms/AgentFastTrackFormSpec.scala
- test/forms/AgentInvitationIdentifyClientFormIrvSpec.scala
- test/forms/AgentInvitationIdentifyClientFormVatSpec.scala
> [APB-3300][SM]: Cleanup form handling in the "agent-invitation-frontend"

- app/uk/gov/hmrc/agentinvitationsfrontend/config/ExternalUrls.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentCancelAuthorisationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsErrorController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsFastTrackInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsRequestTrackingController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/BaseController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/BaseInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientsMultiInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/testing/TestEndpointsController.scala
- build.sbt
- conf/application.conf
- it/uk/gov/hmrc/agentinvitationsfrontend/connectors/AuthActionsISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationsControllerContinueUrlISpec.scala
- project/plugins.sbt
+ get rid of compiler warning of the deprecated base controller method
+ make base classes abstract
> [AO] tidying up: use ExternalUrls instead of direct url injection

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeAuthController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cancelAuthorisation/authorisation_cancelled.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cancelAuthorisation/confirm_cancel.scala.html
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeAuthControllerISpec.scala
> [APB-3284][SM]: Authorisations cancelled page

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeAuthController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/BaseInvitationController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cancelAuthorisation/no_client_found.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeAuthControllerISpec.scala
> [APB-3310][SM]: No client found error page

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeAuthController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cancelAuthorisation/response_failed.scala.html
- conf/app.routes
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeAuthControllerISpec.scala
> [APB-3357][SM]: Failed deauthorisation - Agent led de auth

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/JourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/journeys/AgentInvitationJourneyController.scala
This PR introduces 2 changes to the FSM controller design: 
- abstracts over authorisation type (who we authorise for)
- simplifies action declaration, getting rid of multiple action builder methods  with implicit request/headerCarrier combinations
> [APB-3386][AO] make fsm action declaration cleaner

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/retired/AgentsInvitationController.scala
Jenkins build was failing on a test due to a fire-and-forget style DB update
> [APB-3538][JR] Wait for session update to be saved before returning response

- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/retired/ClientsMultiInvitationsControllerISpec.scala
Reverts hmrc/agent-invitations-frontend#500
> Revert "[APB-3534][PT]: Update Service Content"

- app/assets/stylesheets/styles.scss
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsRequestTrackingController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/track.scala.html
* missing border at top of table
* overshooting last page should just send you to the last page
> [APB-4456][SJM] QA feedback

- app/FrontendModule.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/connectors/AgentSuspensionConnector.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/FeatureFlags.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationJourneyModel.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationJourneyStateFormats.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/agent_suspended.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/stubs/AgentSuspensionStubs.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/support/BaseISpec.scala
- test/journeys/AgentInvitationJourneyModelSpec.scala
- test/journeys/AgentInvitationJourneyStateFormatsSpec.scala
The suspension feature is not available yet so has been stubbed out in agents external stubs, this feature should therefore be flagged off in QA and PRODUCTION!
> [APB-4556][MP] Add error page after selecting service if agent is suspended for this service

- app/assets/javascripts/ai-fe.js
- app/assets/javascripts/session-timeout.js
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/TimeoutController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/govuk_wrapper.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/main_template.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/timed_out.scala.html
- conf/app.routes
- conf/messages
different bahaviour depending on whether the pop up times out or the user manually signs out
> [APB-4653][MP] fixing timeout

- conf/messages.en
Reverts hmrc/agent-invitations-frontend#696
> Revert "[SD] Fix CGT content"

- conf/messages.en
change references of 'property disposals' to 'property account'
> APB-4810 CGT: Change of service name

- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cancelAuthorisation/business_select_service.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cancelAuthorisation/response_failed.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cgtRef_notFound.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/delete.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/invitation_creation_failed.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/not_matched.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/review_authorisations.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/select_single_service.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/cannot_confirm_identity.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/confirm_decline.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/gg_user_id_needed.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/cancel_authorisation_problem.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/confirm_cancel.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/confirm_cancel_authorisation.scala.html
- conf/messages.cy
- conf/messages.en
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyControllerISpec.scala
Missing Welsh keys to be requested:
invitation-sent.step1.personal.paye-vat=
invitation-sent.step1.personal.vat=
confirm-authorisation-cancelled.p1.HMRC-CGT-PD=
confirm-authorisation-cancelled.p1.track.HMRC-CGT-PD=
> APB-5332 [CS] update service names

- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationFastTrackJourneyControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeauthJourneyControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsRequestTrackingControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientInvitationJourneyControllerISpec.scala
also wow some of these files are long :o
> APB-5332-fix [CS] update Intergration tests

- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/invitation_sent.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/preauth_form.scala.html
- conf/messages.cy
- conf/messages.en
fixes tab-nabbing vulnerability from DAST report
> [CS] | add rel=”noreferrer noopener”

- app/uk/gov/hmrc/agentinvitationsfrontend/models/SuspensionDetails.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyControllerISpec.scala
to support client insolvency release
> APB-5653 [CS] Revert AGSV in suspension check

- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/review_authorisations.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/ConfirmTermsPageConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/check_answers.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/confirm_terms_multi.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/warm_up.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/components/InputSingleCheckbox.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/track.scala.html
- conf/app.routes
style of consent headings
consent now submits correctly
CYA consent change link changed to GET (since it's now a link, not a form submit)
> APB-5517 [CS] | fix consent page

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationFastTrackJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationFastTrackJourneyModel.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationJourneyModel.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/PendingAuthorisationExistsPageConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/pending_authorisation_exists.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/components/h1.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/components/h2.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/components/p.scala.html
- build.sbt
- conf/messages.cy
- conf/messages.en
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationFastTrackJourneyControllerISpec.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationJourneyControllerISpec.scala
- test/journeys/AgentInvitationFastTrackJourneyModelSpec.scala
- test/journeys/AgentInvitationFastTrackJourneyStateFormatsSpec.scala
- test/journeys/AgentInvitationJourneyModelSpec.scala
- test/journeys/AgentInvitationJourneyStateFormatsSpec.scala
Apb 5617 Add client name and auth invitation request link to page
> Apb 5617 Add client name and auth invitation request link to page

- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/track.scala.html
so it does not clash with preauth_form or cancel_auth_form
haven't been able to run the tests because I'm still trying to get mongo to work, so if someone doesn't mind doing that? It's a v small change
> [CS] | change track page id

- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/cgtRef_notFound.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/not_signed_up.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/complete.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/session_lost.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/some_responses_failed.scala.html
> Bug fix bracket

- conf/messages.cy
- conf/messages.en
- it/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientInvitationJourneyControllerISpec.scala
> APB-6256 [CS] remove MTD VAT refs

- app/uk/gov/hmrc/agentinvitationsfrontend/config/AppConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentInvitationFastTrackJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/FeatureFlags.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationFastTrackJourneyModel.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationJourneyModel.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/ClientInvitationJourneyModel.scala
- conf/application.conf
- it/uk/gov/hmrc/agentinvitationsfrontend/support/BaseISpec.scala
- project/AppDependencies.scala
- test/journeys/AgentInvitationFastTrackJourneyModelSpec.scala
- test/journeys/AgentInvitationJourneyModelSpec.scala
- test/journeys/ClientInvitationJourneyModelSpec.scala
- test/support/TestFeatureFlags.scala
revert play-frontend-hmrc to 5.5.0
> APB-6879 [CS] remove agent-suspensions FF

- app/uk/gov/hmrc/agentinvitationsfrontend/config/AppConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentLedDeauthJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/AgentsRequestTrackingController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/FeatureFlags.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/testing/TestEndpointsController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationFastTrackJourneyModel.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentInvitationJourneyService.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/AgentLedDeauthJourneyService.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/journeys/ClientInvitationJourneyService.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/ClientConsent.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/models/Invitation.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/repository/MongoSessionStore.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/TrackPageConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/track/track.scala.html
- conf/application.conf
- test/journeys/AgentInvitationJourneyStateFormatsSpec.scala
- test/journeys/AgentLedDeauthJourneyStateFormatsSpec.scala
- test/support/TestFeatureFlags.scala
- removes `show-agent-led-de-auth` and `enable-track-cancel-auth-action`
> APB-6848 [CS] remove 2 old feature flags

- app/ErrorHandler.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/CheckDetailsPageConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/ClientTypePageConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/ReviewAuthorisationsPageConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/agents/SelectServicePageConfig.scala
- build.sbt
- conf/app.routes
- it/uk/gov/hmrc/agentinvitationsfrontend/support/BaseISpec.scala
+  remove silencer plugin and use scalacOptions
> [CS] update HeaderCarrierConverter

- app/uk/gov/hmrc/agentinvitationsfrontend/config/AppConfig.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/config/ExternalUrls.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/MainTemplate.scala.html
- app/uk/gov/hmrc/agentinvitationsfrontend/views/fullWidthMainContentLayout.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
bump play-frontend-hmrc to 7.7
> live [CS] remove beta banner

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/ClientInvitationJourneyController.scala
- app/uk/gov/hmrc/agentinvitationsfrontend/views/clients/check_answers.scala.html
- conf/app.routes
- conf/application.conf
fixes CYA change link bug introduced in version 1.2.0
> APB-7249 [CS] update CYA change link

- app/uk/gov/hmrc/agentinvitationsfrontend/controllers/DateFieldHelper.scala
Fix bug where a day or month entered with too many leading zeros could cause an exception
> Date entry bug fix

- app/uk/gov/hmrc/agentinvitationsfrontend/connectors/AgentClientAuthorisationConnector.scala
- it/uk/gov/hmrc/agentinvitationsfrontend/stubs/ACAStubs.scala
I also ran the tests in `agents-acceptance-tests` alongside this - let me know if that's not the correct AT pack
> APB-8629 Change expected err code when querying agency name
